"""create tables

Revision ID: 1755952812
Revises: 
Create Date: 2025-08-23 09:40:12.485286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1755952812'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = ('default',)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('board', sa.String(), nullable=False),
    sa.Column('wifi_ssid', sa.String(), nullable=False),
    sa.Column('wifi_password', sa.String(), nullable=True),
    sa.Column('ota_password', sa.String(), nullable=True),
    sa.Column('config_file', sa.String(), nullable=False),
    sa.Column('ap_ssid', sa.String(), nullable=False),
    sa.Column('ap_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ap_ssid'),
    sa.UniqueConstraint('config_file'),
    sa.UniqueConstraint('name')
    )
    op.create_table('component',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_type', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('config_json', sa.String(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('component')
    op.drop_table('device')
    # ### end Alembic commands ###
